Feat/p2022 355/add header component test
intive/patronage22_web_auto_szczecin pull request #14
Opened 2022-03-07 13:44 UTC by KlaudiaLapcionek

2022-03-07 20:05 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/HomePage.java
> +        return headerComponent.isDisplayed(); }
minor: code formatting

2022-03-07 20:05 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/HomePage.java
> +    public boolean logoIsDisplayed() { return logo.isDisplayed(); }
minor: code formatting

2022-03-07 20:05 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/HomePage.java
> +        return headerTitle.getText();
the name of the method suggests it will return boolean value

2022-03-07 20:05 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/HomePage.java
> +        return headerComponent.getCssValue("position");
the name of the method suggests it will return boolean value

2022-03-07 20:05 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/HomePage.java
> +    public String headerBackgroundIsSet() {
the name of the method suggests it will return boolean value

2022-03-08 09:50 UTC, KlaudiaLapcionek commented on src/test/java/com/intive/template/pages/HomePage.java
> +        return headerComponent.isDisplayed(); }
Thanks I fixed it.

2022-03-08 09:50 UTC, KlaudiaLapcionek commented on src/test/java/com/intive/template/pages/HomePage.java
> +        return headerTitle.getText();
You're right. I fixed it. Thanks

2022-03-09 18:59 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/steps/HomePageStepdefs.java
> +        Assert.assertEquals("Title of header is not visible", homePage.getHeaderTitleText(), titleOfHeader);
Once you use ham crest assertions, once normal assertion be consistent :)

2022-03-09 19:04 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/steps/HomePageStepdefs.java
> +        Assert.assertEquals("Title of header is not visible", homePage.getHeaderTitleText(), titleOfHeader);
http://hamcrest.org/JavaHamcrest/tutorial

2022-03-09 19:04 UTC, MarekPawlowskiQA requested changes
Change assertion to Hamcrest ones :)

2022-03-09 19:53 UTC, KlaudiaLapcionek commented on src/test/java/com/intive/template/steps/HomePageStepdefs.java
> +        Assert.assertEquals("Title of header is not visible", homePage.getHeaderTitleText(), titleOfHeader);
You are right. I changed that. Thanks :)

2022-03-10 08:09 UTC, MarekPawlowskiQA approved these changes
lgtm :)

2022-03-10 08:18 UTC, ospatrycja commented
Lgtm :)

2022-03-10 08:18 UTC, ospatrycja approved these changes
Lgtm :)

2022-03-10 08:36 UTC, merged