[QA-Auto] Automate context menu component
intive/patronage22_web_auto_szczecin pull request #15
Opened 2022-03-07 19:46 UTC by WDaniszewska

2022-03-08 13:38 UTC, KlaudiaLapcionek submitted a review, later dismissed
Lgtm :)

2022-03-09 19:10 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    @FindBy(how = How.CSS, using = "#__next > div > main > div.sc-3c8adf34-0.isvBOn > div:nth-child(2) > div > div > button > span")
Most probably this number will change, whenever new web app is deployed. Try to find different selector. 
But plus for CSS : P

2022-03-09 19:10 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    @FindBy(how = How.CSS, using = "#__next > div > main > div.sc-3c8adf34-0.isvBOn > div:nth-child(2) > div > div > nav > ul > li:nth-child(1)")
Same here, in NEXT JS framework this values change, and are generated "randomly"

2022-03-09 19:12 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    //returns true if the context menu is closed and false if it is displayed
unnecessary :) comments are ok, but in this case method is self explanatory

2022-03-09 19:13 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean contextMenuShouldBeClose() {
isContectMenuClosed() something is or is not

2022-03-09 19:15 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean contextMenuShouldBeClose() {
btw not many people in IT know this but..... in some way it is related to this problem https://en.wikipedia.org/wiki/Is–ought_problem : D

2022-03-09 19:16 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean contextMenuShouldBeClose() {
But still in method names, pure facts, not wishfull words are used.

2022-03-09 19:16 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean listContainsTwoItems() {
isListContainsTwoItems()

2022-03-09 19:16 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean contextMenuIsOpen() {
isContectMenuOpen

2022-03-09 19:19 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +        int i = optionsList.size();
I would go with more informative variable

2022-03-09 19:20 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +            if (!li.isDisplayed() || i != 2) {
Hmmin this case maybe small comment would be needed, for example why this is used i != 2 ?

2022-03-09 19:21 UTC, MarekPawlowskiQA requested changes
Requested changes in comments

2022-03-09 21:09 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
I changed it as you wrote.

2022-03-09 21:10 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    @FindBy(how = How.CSS, using = "#__next > div > main > div.sc-3c8adf34-0.isvBOn > div:nth-child(2) > div > div > button > span")
I found another selector.

2022-03-09 21:10 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    @FindBy(how = How.CSS, using = "#__next > div > main > div.sc-3c8adf34-0.isvBOn > div:nth-child(2) > div > div > nav > ul > li:nth-child(1)")
done.

2022-03-09 21:11 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    //returns true if the context menu is closed and false if it is displayed
I removed this comment.

2022-03-09 21:11 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean contextMenuShouldBeClose() {
I fix it :)

2022-03-09 21:12 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean listContainsTwoItems() {
done

2022-03-09 21:12 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean contextMenuIsOpen() {
done

2022-03-09 21:12 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +        System.out.println(i);
done

2022-03-09 21:12 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +        int i = optionsList.size();
I changed it

2022-03-09 21:13 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +            if (!li.isDisplayed() || i != 2) {
I added a comment

2022-03-10 08:08 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean isListContainsTwoItems() {
You can make this function more general,  isListContainsItems(itemsNumber) and than, decide how many items you want to check.

2022-03-10 20:22 UTC, WDaniszewska commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    public boolean isListContainsTwoItems() {
I made changes :)

2022-03-11 13:05 UTC, MarekPawlowskiQA approved these changes
lgtm :)

2022-03-11 16:54 UTC, KlaudiaLapcionek approved these changes
Lgtm :)

2022-03-12 16:03 UTC, ospatrycja approved these changes
lgtm :)

2022-03-12 16:19 UTC, merged