[ADD] P2022-312 Add gitWorkflow.md file
intive/patronage22_web_auto_szczecin pull request #2
Opened 2022-01-23 15:44 UTC by WDaniszewska

Added file containing description of Git workflow.

2022-01-23 16:27 UTC, MarekPawlowskiQA requested changes
Requested very minor changes

2022-01-23 16:27 UTC, MarekPawlowskiQA commented on gitWorkflow.md
> +feat/\{task number\}/\{task name\}
Please remove "/"
 
Example should look like feat/{task number}/{task name}

2022-01-23 16:27 UTC, MarekPawlowskiQA commented on gitWorkflow.md
> +[ADD] \{Task number\} + short informational description
Also here: [ADD]{Task number} + short informational description

2022-01-23 18:23 UTC, WDaniszewska commented on gitWorkflow.md
> +feat/\{task number\}/\{task name\}
Done

2022-01-23 18:23 UTC, WDaniszewska commented on gitWorkflow.md
> +[ADD] \{Task number\} + short informational description
Done

2022-01-23 18:24 UTC, WDaniszewska reviewed
Done

2022-01-23 18:48 UTC, ospatrycja approved these changes

2022-01-23 18:51 UTC, KrzysztofGajQA approved these changes
not LGTM at the moment

2022-01-23 18:57 UTC, KrzysztofGajQA requested changes
Hi, there is a typo in line 28, in word "resolved". The correct word should be "resolve".

2022-01-23 19:30 UTC, KrzysztofGajQA commented
Hi, the word from line 28 should be in line 29 and vice-versa ;)
![feat_P2022-313_correction](https://user-images.githubusercontent.com/97545830/150694865-1b2c44f0-c15f-4401-b78e-aac586ed816c.png)

2022-01-23 19:45 UTC, WDaniszewska commented
> Hi, the word from line 28 should be in line 29 and vice-versa ;) ![feat_P2022-313_correction](https://user-images.githubusercontent.com/97545830/150694865-1b2c44f0-c15f-4401-b78e-aac586ed816c.png)

2022-01-23 20:22 UTC, KrzysztofGajQA submitted a review, later dismissed
All green to me  👍  Good to squash!

2022-01-23 21:19 UTC, MarekPawlowskiQA submitted a review, later dismissed
lgtm

2022-01-23 22:52 UTC, annaslodkowska commented on gitWorkflow.md
> +When PR is created everyone should find time to check it (whenever its possible).
Should be "it's" or "it is"

2022-01-24 07:45 UTC, WDaniszewska commented on gitWorkflow.md
> +When PR is created everyone should find time to check it (whenever its possible).
Done

2022-01-24 07:46 UTC, MarekPawlowskiQA approved these changes
still lgtm. btw I know dismissing approve is annoying after each change, but later you will get used to it. If this will start to be a real problem I will remove this option  :)

2022-01-24 16:49 UTC, ospatrycja approved these changes

2022-01-24 16:57 UTC, KrzysztofGajQA approved these changes
LGTM :)

2022-01-24 17:07 UTC, merged