[FIX]P2022-1836 Maintenance of tests failing after changes part 3
intive/patronage22_web_auto_szczecin pull request #20
Opened 2022-03-20 13:43 UTC by KrzysztofGajQA

Fixed one selector for context menu, it should work now.

2022-03-20 16:38 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    @FindBy(how = How.XPATH, using = "//*[@id=\"01FV757GXRK6A9MMFA1EMA2V7D\"]")
Change this xptah to something else, I mentioned this in recent PR and it seems I have right, this id will change very often, and it is very unstable as locator. Find another way, to handle this element.

2022-03-20 16:39 UTC, MarekPawlowskiQA requested changes
Selector must be rewritten

2022-03-20 20:36 UTC, KrzysztofGajQA commented
@MarekPawlowskiQA  I've changed the unstable selector you have mentioned to CLASS_NAME.

2022-03-21 07:28 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    @FindBy(how = How.CLASS_NAME, using = "sc-5ba0824a-3")
still the same :) next.js will generate random number name very time app is build, this will only work once

2022-03-21 18:57 UTC, KrzysztofGajQA commented
@MarekPawlowskiQA I've changed it again ;) Is it better now?

2022-03-21 20:14 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/ContextMenuPage.java
> +    @FindBy(how = How.XPATH, using = "//div[2]//div[1]//div[1]//nav[1]")
I mean it is still bad, but wihout any proper selectors, this is max we can do :)

2022-03-21 20:15 UTC, MarekPawlowskiQA approved these changes
OK :)

2022-03-22 10:19 UTC, WDaniszewska approved these changes
It's still xpath, but as Marek says, for now we don't have much choice, so lgtm :)

2022-03-22 11:57 UTC, merged