P2022-313 - attach test automation framework to proper url + sanity
intive/patronage22_web_auto_szczecin pull request #3
Opened 2022-01-25 17:40 UTC by ospatrycja

Add test to open patronage page.
Remove sample tests.

2022-01-25 20:20 UTC, KlaudiaLapcionek approved these changes

2022-01-26 08:36 UTC, MarekPawlowskiQA requested changes
Really nice, I would change some things, more in comments.

2022-01-26 08:36 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/BasePage.java
> +    private void setupTimeouts() {
Ok two things about that:
1. If we want to make something like this it should be in driver class, as this setup is about whole driver behaviour. (in other case this method will run anytime the page object hmm object is created)  
2. But we don't want this: I would leave default timeouts, as there is no specification how fast web should load https://w3c.github.io/webdriver/#timeouts .Please remove it.

2022-01-26 08:36 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/PatronagePage.java
> +public class PatronagePage extends BasePage {
I understand the idea, but let's change to HomePage to prepare for further development

2022-01-26 08:36 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/PatronagePage.java
> +    private static final String PATRONAGE_URL = "https://patronage22-szczecin-js.vercel.app/";
Nice,  CAPS because it is constant, and it will not change :)

2022-01-26 08:36 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/PatronagePage.java
> +    public boolean patronagePageIsOpened() {
[QUESTION] Do this method really check if **Patronage page** is opened ? 
After answering : change name to proper one

2022-01-26 08:36 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/steps/PatronageStepdefs.java
> +        assertThat("Patronage page is opened", patronagePage.patronagePageIsOpened(), is(true));
Related to previous question about "is Patronage page opened" , Do we really check in this test if Patronage web was opened. Ee probably need here another assertion.

2022-01-26 08:36 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/steps/PatronageStepdefs.java
> +        assertThat("Patronage page is opened", patronagePage.patronagePageIsOpened(), is(true));
Nice, usage of hamcrest assertions btw. Everything is there.

2022-01-26 08:36 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/PatronagePage.java
> +    public void openPatronagePage() {
Nice for now, later we can think if we we need different solution for that, but for the time being 100% agree.

2022-01-26 08:37 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/PatronagePage.java
> +    private static final String PATRONAGE_URL = "https://patronage22-szczecin-js.vercel.app/";
at leats we can assume it will not change :)

2022-01-26 17:44 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/PatronagePage.java
> +    public boolean patronagePageIsOpened() {
No. According to the [documentation ](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState) this method checks if the document and all sub-resources have finished loading. 

I will change the method name to `isPageLoaded()`.

2022-01-26 18:09 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/BasePage.java
> +    private void setupTimeouts() {
Removed

2022-01-26 18:09 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/PatronagePage.java
> +public class PatronagePage extends BasePage {
Renamed

2022-01-26 18:10 UTC, ospatrycja commented on src/test/java/com/intive/template/steps/PatronageStepdefs.java
> +        assertThat("Patronage page is opened", patronagePage.patronagePageIsOpened(), is(true));
Added new assertion

2022-01-26 18:42 UTC, KlaudiaLapcionek approved these changes

2022-01-26 19:49 UTC, MarekPawlowskiQA commented on src/test/resources/features/homePage.feature
> +    Then Home page is loaded and opened
In Gherkin, if we would like to be "pure proper" it should like: 
**Then** Home page is loaded
**And** Home page is opened
But I agree to this implementation, we can ignore this and leave it as one step, it is more functional

2022-01-26 19:51 UTC, MarekPawlowskiQA approved these changes
lgtm :) remember to squash when merging and remember to follow gitflow in naming the squash commit

2022-01-26 20:04 UTC, merged