[MOD] P2022-824 Modify smoke test to check header component
intive/patronage22_web_auto_szczecin pull request #6
Opened 2022-02-07 18:09 UTC by WDaniszewska

2022-02-07 19:11 UTC, ospatrycja requested changes

2022-02-07 19:11 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/HomePage.java
> +    WebElement headerComponent;
I think code formatting is incorrect here. Missing empty line and function body could be also in new line

2022-02-07 19:11 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/HomePage.java
> +    public void headerIsDisplayed() { Assert.assertTrue(headerComponent.isDisplayed()); }
I think we should move this method to the bottom of the class.

2022-02-07 19:11 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/HomePage.java
> +    public void headerIsDisplayed() { Assert.assertTrue(headerComponent.isDisplayed()); }
I think assertion should be used in `Stepdefs` class and this method should return value (boolean) instead of void.

2022-02-07 19:11 UTC, ospatrycja commented on src/test/resources/features/homePage.feature
> +    Then Header component is visible
I'm not sure if this step should be used in `Open home page` scenario. Maybe we should add new scenario for header component?

2022-02-07 19:22 UTC, MarekPawlowskiAuto commented on src/test/java/com/intive/template/pages/HomePage.java
> +    WebElement headerComponent;
ctrl+alt+L (will help you to format code) but double check it im not sure if this is proper shortcut for windows InteliJ. For Mac is cmd+option+shift+L

2022-02-08 20:47 UTC, WDaniszewska commented on src/test/resources/features/homePage.feature
> +    Then Header component is visible
I analyzed the AC and according to them I should modify the existing one, but I think that adding a new scenario will be clearer. After talking with Patrycja, we agreed that I will add a second scenario and the AC should be modified.

2022-02-08 21:08 UTC, MarekPawlowskiAuto commented on src/test/java/com/intive/template/steps/HomePageStepdefs.java
> +        Assert.assertTrue(homePage.headerIsDisplayed());
Change to hamcrest assertion to be more consistent, example you can see in smoke tests

2022-02-09 18:52 UTC, ospatrycja approved these changes
Looks good to me, one small thing to improve is the assertion Marek mentioned :)

2022-02-09 19:21 UTC, WDaniszewska commented on src/test/java/com/intive/template/steps/HomePageStepdefs.java
> +        Assert.assertTrue(homePage.headerIsDisplayed());
Done

2022-02-09 19:29 UTC, MarekPawlowskiAuto approved these changes
lgtm :)

We will need change selector to something more stable later. 
Also we need to talk about naming convention in feature file but for now, ok for me.

2022-02-09 20:10 UTC, ospatrycja approved these changes

2022-02-10 07:15 UTC, MarekPawlowskiQA approved these changes
lgtm 2 "I have too many git accounts......."

2022-02-10 08:36 UTC, merged